name: Deploy PHP to Azure Web App

on: [push]

# put this in the .github/workflows folder
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: prater # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "./react/public" # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install & build
        run: |
          npm install
          npm run build
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          source_dir: './react/build'
          container_name: '$web'
          connection_string: ${{ secrets.AZURE_STORAGE }}
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          sync: 'true'
